- name: Main Playbook
  hosts: protohosts
  vars:
    swap_size_mb: 1024
    repo_home: "/home/{{ansible_user}}/protoxpress"
  tasks:
    - name: Initial setup
      ansible.builtin.include_tasks:
        file: tasks/initial_setup.yml
    
    - name: SWAP
      ansible.builtin.include_tasks:
        file: tasks/swap.yml

    - name: SSH
      ansible.builtin.include_tasks:
        file: tasks/ssh.yml

    - name: pyenv
      ansible.builtin.include_tasks:
        file: tasks/pyenv.yml

    - name: project
      ansible.builtin.include_tasks:
        file: tasks/project.yml

    - name: nginx
      ansible.builtin.include_tasks:
        file: tasks/nginx.yml

    - name: systemd
      ansible.builtin.include_tasks:
        file: tasks/systemd.yml
