services:
  podbrain:
    container_name: "podbrain"
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/srv/app
    ports:
      - 5000:5000
    command: /bin/bash -c  "flask --app /srv/app run --debug --host 0.0.0.0"

  nginx:
    container_name: "podbrain-nginx"
    image: nginx:latest
    volumes:
      - ./config/docker.nginx.conf:/etc/nginx/nginx.conf
      - ./static:/srv/static/
    ports:
      - 9000:80
    depends_on:
      - podbrain
