- name: Update apt-get repo and cache
  become: true
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrade all apt packages
  become: true
  apt: 
    upgrade: dist

- name: Install packages
  become: true
  apt:
    pkg:
      - git
      - vim
      - curl

- name: Setup config directory
  become: true
  file:
    path: /etc/ansible
    state: directory
    owner: "{{ ansible_user }}"