- name: Install nginx
  become: true
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Move nginx config
  become: true
  file:
    src: "{{repo_home}}/pod/brain/config/nginx.conf"
    dest: /etc/nginx/nginx.conf
    state: link

- name: Ensure nginx is running
  become: true
  systemd:
    name: nginx
    state: restarted
    enabled: true