- name: Clone project
  git:
    repo: 'https://github.com/Sorjak/protoxpress.git'
    dest: "{{ repo_home }}"
    clone: yes
    update: yes

- name: Create app dir symlink
  become: true
  file:
    src: "{{ repo_home }}/pod/brain/app/"
    dest: /srv/app
    owner: "{{ ansible_user }}"
    state: link

- name: Create static dir symlink
  become: true
  file:
    src: "{{ repo_home }}/pod/brain/static/"
    dest: /srv/static
    owner: "{{ ansible_user }}"
    state: link

- name: Create virtual environment for app
  shell: "$HOME/.pyenv/versions/3.12.9/bin/python -m venv /srv/app/.venv"
  args:
    creates: /srv/app/.venv

- name: Install requirements in venv
  pip:
    requirements: "{{ repo_home }}/pod/brain/requirements.txt"
    virtualenv: /srv/app/.venv