- name: Add systemd unit file
  become: true
  file:
    src: "{{repo_home}}/pod/brain/config/podbrain.service"
    dest: /etc/systemd/system/podbrain.service
    state: link

- name: Just force systemd to reread configs
  become: true
  systemd_service:
    daemon_reload: true

- name: Ensure app service is running
  become: true
  systemd:
    name: podbrain
    state: started
    enabled: true
